site_name: PhyloNext

site_author: Vladimir Mikryukov, Kessy Abarenkov
site_description: A pipeline for phylogenetic diversity analysis of GBIF-mediated data.
copyright: "Copyright © 2022 Vladimir Mikryukov, Kessy Abarenkov. All rights reserved."

site_url: https://phylonext.github.io/
repo_url: https://github.com/vmikk/PhyloNext

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  favicon: assets/favicon.ico
  logo: assets/PhyloNext_logo.png
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  features:

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes
  - admonition
  - toc:
      permalink: True
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - 'Introduction':         'index.md'
  - 'Installation':         'installation.md'
  - 'Basic Usage':          'usage.md'
  - 'Output overview':      'outputs.md'
  - 'Pipeline parameters':  'parameters.md'
  - 'Troubleshooting':      'troubleshooting.md'
  - 'Web GUI':              'webgui.md'
  - 'Post processing':      'post.md'
  - 'Acknowledgments':      'acknowledgements.md'

